# Generated by Django 5.2.4 on 2025-07-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_sexe_utilisateur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(default=774825025, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
